#!/bin/sh

#cd /dev
#mknod -m 666 tty1 c 4 1
#mknod -m 666 tty2 c 4 2
#mknod -m 666 tty3 c 4 3
#mknod -m 666 tty4 c 4 4
#mknod -m 666 console c 5 1
#mknod -m 666 null c 1 3
#cd /

mount -t proc proc /proc

mount -t sysfs sysfs /sys

mount -t tmpfs tmpfs /dev

mkdir -p /dev/pts

mount -t devpts devpts /dev/pts

mount -t debugfs none /sys/kernel/debug

/sbin/mdev -s

# need enable
echo /sbin/mdev > /proc/sys/kernel/hotplug

telnetd

ifconfig eth0 192.168.1.101 netmask 255.255.255.0
