
SRC := $(wildcard *.c)
OBJ := $(patsubst %.c,%.o,$(SRC))
ELF := $(patsubst %.c,%.elf,$(SRC))


all:
	@echo "hell makefile in leetcode\n"
	@echo "SRC = $(SRC)\n"
	@echo "OBJ = $(OBJ)\n"
	@echo "ELF = $(ELF)\n"
