#!/usr/bin/expect -f
# ssh连接
# 2024-03-11

set timeout 10

# spawn：启动新进程进行交互式运行，后续命令都是和spawn创建的进程交互
spawn ssh root@192.168.0.2

expect {
    "password:" {send "root\r"; exp_continue}
    "root@mkpart" {}
    timeout {exit 1}
}

send "cd /home/root\r"
expect {
    "root@mkpart" {}
    timeout {exit 1}
}

puts "\[hx-debug(2)\] will sleep 10s"
sleep 10

send "rm test01; touch test02\r"
expect {
    "root@mkpart" {puts "\[hx-debug(2)\] touch test02 success"}
    timeout {exit 1}
}

send "exit\r"
expect {
    "closed" {puts "\[hx-debug(2)\] ssh connection is closed"}
    timeout {exit 1}
}

interact
